data/urls.py
from django.conf.urls import url


from . import views


urlpatterns = [
	url(r'^datasiswa/$',views.student,name='dataSiswa'),
	url(r'^dataguru/$',views.teacher,name='dataGuru'),
]

home/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf.urls import handler404,handler500
from . import views
from django.views.defaults import page_not_found
from django.conf import settings
from django.views.static import serve 
import django.views.defaults
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [

    path('delete/<delete_id>',views.delete , name="delete"),
    path('update/<update_id>',views.update , name="update"),
    path('detail/<slugInput>',views.detail),
    path('',views.index,name='index'),
    
    path('create/',views.create,name='create'),
    path('login/',views.loginView,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logoutView,name='logout'),

	 
    #path('404/', views.error404),

    path('profile/',views.profil,name='profile'),
    path('profile/ganti_foto/',views.ganti_foto,name='ganti_foto'),
    path('register_bio/', views.register_bio_view ,name="register_bio"),
    path('pinjam_buku/',views.peminjaman_buku,name="pinjam"),
    path('daftar_pinjam_buku/',views.tampil_buku_dipinjam,name="databuku"),
    path('fail/',views.fail,name="fail"),
    path('success/',views.success,name="success"),
    path('empty/',views.empty,name="empty"),
    path('down_file/',views.down_file,name="down_file"),
  


    path('tampil_tabel/', views.tampil_tabel,name='data_buku'),   
    path('daftar_buku/', views.daftar_buku, name ='daftar_buku'),
    path('daftar_peminjam/', views.daftar_peminjam, name ='daftar_peminjam'),

  #url(r'^tampil_tabel/$', views.tampil_tabel,name='data_buku'), 
  #url(r'^daftar_suplier/', views.daftar_suplier_buku, name ='suplier'),
  #url(r'^daftar_penyumbang/', views.daftar_penyumbang_buku, name ='penyumbang'),


]


handler404 = 'home.views.handler404'

handler500 = 'home.views.handler500'


soshiki/urls.py

from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.conf.urls import handler404
from django.views.static import serve 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('media/<path>.*', serve,{'document_root': settings.MEDIA_ROOT}), 
	# path('static/<path>.*', serve,{'document_root': settings.STATIC_ROOT}), 
    path('home/', include(('home.urls', 'home'), namespace='home')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    #path('data/', include(('data.urls', 'data'), namespace='data')),
    path('kisara/', include(('kisara.urls', 'kisara'), namespace='kisara')),
    path('about/',views.about,name="about"),
    path('',views.index,name="index"),


]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
class PostNewsForm(forms.ModelForm):
	class Meta:
		model = PostNews
		fields = [
		'judul',
		'isi',
		'thumb',
		]
		widgets = {

		'judul':forms.TextInput(
			attrs = {
			'class':'form-control',
			'placeholder':'fill with title of News',


			}



			),
		'isi':forms.TextInput(
			attrs = {
			'class':'form-control',
			'placeholder':'fill this body of News',

			}
			


			),
		'thumb':forms.FileInput(
			attrs = {
			'class':'form-control',
			'id': 'inputGroupFile01',	
			
			}
			 


			),


		}
class CreateUser(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2']
		widgets = {

			'username':forms.TextInput(
			attrs = {
			'class':'form-control',
			'placeholder':'fill with title of News',
			'autocomplete':"off",

			}



			),
			'email':forms.TextInput(
			attrs = {
			'class':'form-control',
			'placeholder':'fill with title of News',
			'autocomplete':"off",

			}



			),
			'password1':forms.PasswordInput(
			attrs = {
			'class':'form-control form-control-user',
			'placeholder':'fill with title of News',
			'autocomplete':"off",

			}



			),
			'password2':forms.PasswordInput(
			attrs = {
			'class':'form-control form-control-user',
			'placeholder':'fill with title of News',
			'autocomplete':"off",

			}



			),

		}
		def __init__(self,*args,**kwargs):
			super(CreateUser,self).__init__(*args,**kwargs)
			self.fields['password1'].widget = PasswordInput(attrs={'class':'form-control'})
			self.fields['password2'].widget = PasswordInput(attrs={'class':'form-control'})
			for visible in self.visible_fields():
				visible.field.widget.attrs['class'] = 'form-control'





class anggota_form(forms.ModelForm):
	class Meta:
		model = biodata

		fields = ['nama','jenis_kelamin','tgl_lahir','alamat','no_telepon','email','status']
		labels = {

			'nama':'Nama Lengkap',
			'jenis_kelamin':'Jenis Kelamin',
			'tgl_lahir':'Tanggal Lahir',
			'alamat':'Alamat',
			'no_telepon':'No Telepon',
			'email':'Email',
			'status':'status',

		}
		error_messages = {

			'nama':{
				'required':'Anda harus mengisi nama'
			},
			'jenis_kelamin':{
				'required':'Anda harus memilih jenis kelamin'
			},
			'tgl_lahir':{
				'required':'Anda harus mengisi tanggal lahir'
			},
			'alamat':{
				'required':'Anda harus mengisi alamat'
			},
			'no_telepon':{
				'required':'Anda harus mengisi nomer telepon'
			},
			'email':{
				'required':'Anda harus mengisi email'
			},
			'status':{
				'required':'Anda harus memilih status'
			}
		}
		# tgl_lahir = forms.DateField(
  #       input_formats=['%Y-%m-%d'],
  #       widget=forms.DateInput(attrs={
  #           'class': 'form-control datetimepicker-input',
  #           'data-target': '#datetimepicker4'
  #       })
  #   )

		#tgl_lahir = forms.DateField(widget= forms.SelectDateWidget(attrs={'class':'form-control',},years= range(1945,2019,1)))
		#tgl_lahir = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
		widgets = {
		'nama':forms.TextInput(attrs = {'class':'form-control',}),
		'tgl_lahir':forms.SelectDateWidget(attrs={'class':'form-control col-sm-4','autocomplete':"off"},years= range(1945,2019,1), ),
		# 'tgl_lahir':forms.DateTimeInput(attrs={
  #           'class': 'form-control datetimepicker-input',
  #           'data-target': '#datetimepicker1'
  #       }),
		'alamat':forms.TextInput(attrs = {'class':'form-control','autocomplete':"off"}),
		'no_telepon':forms.TextInput(attrs = {'class':'form-control','autocomplete':"off"}),
		'email':forms.TextInput(attrs = {'class':'form-control','autocomplete':"off"}),
		
		
		}

# class akun_form(forms.ModelForm):
# 	class Meta:
# 		model = User
# 		fields = ['username','password']



class peminjaman_form(forms.ModelForm):
	class Meta:

		model = transaksi_peminjaman
		
		fields = ['judul_buku']
		labels = {

			'judul_buku':'Judul',

		}

		error_messages = {
			'judul_buku':{
				'required':'anda harus mengisi judul buku'
			},
		}

home/views.py

from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from pyexcel_xls import get_data as xls_get
from pyexcel_xlsx import get_data as xlsx_get
from django.utils.datastructures import MultiValueDictKeyError
from django.http import HttpResponse
from django.urls import reverse_lazy
from .forms import *
from .models import *
from django.shortcuts import get_object_or_404
from django.contrib import messages
import datetime
import sys
from soshiki.settings import BASE_DIR
import os
from django.http import JsonResponse
from soshiki.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
#Post News

def index(request):
	posts = PostNews.objects.all()
	context = {
	'page_title':'HOME',
	'posts':posts,
	}
	paginator = Paginator(posts, 5)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	return render(request,'home/index.html',context)

@login_required
def create(request):
	error = None
	
	forms = PostNewsForm(request.POST,request.FILES) 
	if request.method == 'POST':
		print(request.POST['judul'])
		
		if forms.is_valid():
			forms.save()
			messages.success(request, 'Data Created.')
			return redirect('home:index')
		else :
			return redirect('home:create')
	
	context = {
	"page_title":'CREATE',
	'forms':forms
	}
	return render(request,'home/create.html',context)


def loginView(request):
	context = {
	'page_title':'LOGIN',
	}
	if request.method == 'POST':
		user_log = request.POST['username']
		pass_log = request.POST['password']
		user = authenticate(request,username=user_log,password=pass_log)
		if user is not None:	
			if user.is_active:
				try:
					akun = Akun_perpus.objects.get(akun=user.id)
					login(request, user)

					request.session['anggota_id'] = akun.anggota.id
					request.session['username'] = request.POST['username']
					return redirect('home:index')

				except:
					messages.add_message(request, messages.WARNING, 'Akun ini belum terhubung dengan data anggota, silahkan hubungi administartor')
					return redirect('home:login')

			else:
				messages.add_message(request, messages.WARNING, 'User belum terverifikasi')

		else:
			messages.add_message(request, messages.WARNING, 'Username atau password Anda salah')

	return render(request, 'home/login.html')

	if request.method == 'GET':
		if request.user.is_authenticated():
			return redirect('home:index')

		else :
			return render(request,'home/login.html',context)


def logoutView(request):
	context = {
	'page_title':'LOGOUT',
	}
	if request.method == "POST":

		if request.POST['logout'] =='Submit Query' or 'submit':
			logout(request)

		return redirect('home:index')
	else :
		redirect("home:index")
		
	return render(request,'home/logout.html',context)


def register(request):
	forms = CreateUser(request.POST)
	context = {
	'page_title':'REGISTER',
	'forms':forms,

	}

	if request.method == 'POST':
		print("disini")
		if forms.is_valid():
			new_user = User.objects.create_user(username=forms.cleaned_data['username'],email= forms.cleaned_data['email'],password=forms.cleaned_data['password1'])
			print("Success No Error")
			#send_mail('Welcome to KigameKun Corps','I Hope You enjoy in this website', EMAIL_HOST_USER, [forms.cleaned_data['email']], fail_silently = False)
			return redirect('home:register_bio')
		else :
			print("Have A Error")
			print(forms.errors)

	return render(request,'home/register.html',context)


def detail(request,slugInput):
	posts = PostNews.objects.get(slug=slugInput)
	
	context = {
	'judul':'Detail',
	'contents':'BLOG AREA',
	'posts':posts,

	}
	return render(request,'home/detail.html',context)


@login_required
#@user_passes_test(lambda user:Group.objects.get(name='Guru') in user.groups.all())
def delete(request,delete_id):
	PostNews.objects.filter(id=delete_id).delete()
	messages.success(request, 'Data Deleted.')
	return redirect('home:index')

@login_required
#@user_passes_test(lambda user:Group.objects.get(name='Guru') in user.groups.all())
def update(request,update_id):
	news_update = PostNews.objects.get(id=update_id)
	data = {
	'judul':news_update.judul,	
	}

	forms = PostNewsForm(request.POST or None,initial= data,instance=news_update)
	if request.method == 'POST':
		if forms.is_valid():
			messages.success(request, 'Data Updated.')
			forms.save()
			return redirect('home:index')
	context = {
	'page_title':'Update',
	'forms':forms,
	}
	return render(request,'home/create.html',context)

def forgot_password(request):
    if request.method == 'POST':
        return password_reset(request, 
            from_email=request.POST.get('email'))
    else:
        return render(request, 'home/forgot_password.html')



#END POST NEWS



#AWAL LIBRARY

def tampil_tabel(request):
	#data buku

	daftar_buku = data_buku.objects.all()

	#pagination
	paginator = Paginator(daftar_buku, 10)
	page = request.GET.get('page')
	try:
		daftar_buku = paginator.page(page)
	except PageNotAnInteger:
		daftar_buku = paginator.page(1)
	except EmptyPage:
		daftar_buku = paginator.page(paginator.num_pages)

	#daftar peminjam buku
	daftar_pinjam = data_transaksi_peminjaman.objects.all()

	#pagination
	paginator = Paginator(daftar_pinjam, 5)
	page = request.GET.get('page')
	try:
		daftar_pinjam = paginator.page(page)
	except PageNotAnInteger:
		daftar_pinjam = paginator.page(1)
	except EmptyPage:
		daftar_pinjam = paginator.page(paginator.num_pages)
	
	return render(request, "home/tampil_tabel.html",{'daftar_buku':daftar_buku,'daftar_pinjam':daftar_pinjam,'daftar_suplier':daftar_suplier,'daftar_penyumbang':daftar_penyumbang})


def daftar_buku(request):
    daftar_buku  = data_buku.objects.all()
    data = ""
    company = ''
    if request.method == "POST":
          
        try:
            excel_file = request.FILES["fl"]
        except MultiValueDictKeyError:
            return HttpResponse('Salah')
    
        if (str(excel_file).split(".")[-1] == "xls"):
            data = xls_get(excel_file, column_limit=13)
        elif (str(excel_file).split(".")[-1] == "xlsx"):
            data = xlsx_get(excel_file, column_limit=13)
        else:
            print("salah")
       

        key = ''.join(data.keys())
        solve = data[key]
        solved = 0
        for i in range(len(solve)):
            if len(solve[i]) != 0 :
                solved += 1
            else :
                pass
            
        for i in range(1,solved):
            try :
                data_buku.objects.create(judul_buku=solve[i][1],jenis_buku=solve[i][2],penulis=solve[i][3],tgl_terbit=solve[i][4],penerbit=solve[i][5],jumlah_buku=solve[i][6])
                messages.add_message(request, messages.INFO, 'Buku berhasil ditambahkan')
                return redirect('home:daftar_buku')
            except:
                messages.add_message(request, messages.WARNING, 'Buku gagal ditambahkan')
                return redirect('home:daftar_buku')
    return render(request, 'home/daftar_buku.html',{'daftar_buku':daftar_buku})




def down_file(request):
   
    path = os.path.join(str(BASE_DIR)+'/templates/', 'format.xlsx')

   
    with open(path, 'rb') as model_excel:
        result = model_excel.read()
    response = HttpResponse(result)
    response['Content-Disposition'] = 'attachment; filename=format.xlsx'
    return response


@login_required
def daftar_peminjam(request):

	daftar_peminjam = None
	# obj = data_transaksi_peminjaman.objects.get(id = 1)
	# print(obj)
	if request.method == 'POST':

		daftar_peminjam = data_transaksi_peminjaman.objects.filter(judul_buku = request.POST['judul_buku'])
		
	else:
		daftar_peminjam = data_transaksi_peminjaman.objects.all()
			
		# for i in daftar_peminjam:
		# 	field_name = 'tgl_buku_dipinjam'
		# 	obj =data_transaksi_peminjaman.objects.first()
		# 	field_value = getattr(obj, field_name)
		# 	print("WOOEEEE",field_value)
		
		# for pinjam in daftar_peminjam:
		# 	if pinjam.tgl_buku_dikembalikan is not None :
		# 		datas = data_buku.objects.get(judul_buku=pinjam.judul_buku)
				
		# 		tgl1 = list(map(int,str(pinjam.tgl_buku_dipinjam).split('-')))
		# 		tgl2 = list(map(int,str(pinjam.tgl_buku_dikembalikan).split('-')))
		# 		tg1 = datetime.date(tgl1[0],tgl1[1],tgl1[2])
		# 		tg2 = datetime.date(tgl2[0],tgl2[1],tgl2[2])
		# 		if tg1 == tg2 :
		# 			pass
		# 		else :
		# 			solved = str(tg2 - tg1).split()
		# 			y = int(solved[0])
					
					
		# 			if y > 3 :
				
		# 				x = 3000 * (y - 3)
		# 				if pinjam.denda == x :
							 
		# 					pass
		# 				else :
		# 					pinjam.denda = x
						
							
				
		# 				pinjam.save()
		# 			print("HEII INI DENDA",pinjam.denda)
			
		# 	else :
		# 		print(pinjam.judul_buku," belum dikembalikan")

		#pagination
		paginator = Paginator(daftar_peminjam, 10)
		page = request.GET.get('page')
		try:
			daftar_peminjam = paginator.page(page)
		except PageNotAnInteger:
			daftar_peminjam = paginator.page(1)
		except EmptyPage:
			daftar_peminjam = paginator.page(paginator.num_pages)

	return render(request, 'home/daftar_peminjam.html',{'daftar_peminjam':daftar_peminjam})

@login_required(login_url=settings.LOGIN_URL)

home/templates/home/add_company.html
{% extends 'base.html' %}




{% block contents %}
    
<div class="form-group bmd-form-group">
  <label class="bmd-label-static" 
         for="company_autocomplete_input">Cerca azienda</label>
  <input id="company_autocomplete_input" class="form-control"
         placeholder="Nome azienda" style="width:500px">
</div>
 
<button class="btn btn-raised btn-primary" type="submit"
        style="background-color:#1A88B9;">Aggiungi</button>




<!-- jQuery !-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
<!-- jQuery UI !-->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


<script>
  $(function() {
    $("#company_autocomplete_input").autocomplete({
      source: "{% url 'home:company-autocomplete' %}",
      minLength: 1,
    });
  });
</script>

{% endblock contents %}
    

home/templates/home/create.html
{% extends "base.html" %}
{%load static%}

{% block page_title %}
	{{page_title}}
{% endblock page_title %}

{% block contents %}
	
<div class="container">
	
	<form method="POST" enctype="multipart/form-data">

		{% csrf_token %}
		
		{% for form in forms %}
		
		{% if form.label == "Thumb" %}
		<div class="input-group mb-3">
			<label class="input-group-text" for="inputGroupFile01">Upload</label>
			{{form}}
		  </div>

		  {% else %}
		  	
		<div class="form-group">
			<h4>{{form.label}}</h4> 
			{{form}}
		</div>
		
		{% endif %}
		
		{% endfor %}


		<center><button class="btn btn-success" type="submit">Buat !</button></center>
		<br>
		<br>

		
		


	</form>
</div>


{% endblock contents %}

home/templates/home/daftar_buku.html
{% extends "base.html" %}

{% load cek_tabel_helper %}

{% block contents %}

<div class="col-md-12">
	<div class="card card-plain">
     	<div class="header">
             <h4 class="title">Daftar Buku</h4>                    
        </div>
        <div class="content table-responsive table-full-width">
			    	
			{% if messages %}
    
			{% for message in messages %}
			{% if message.tags %} 
            
            {% if message.tags == "warning" %}
                
			<div class="alert alert-danger  alert-dismissible fade show" role="alert">
				<strong>Voilla </strong> {{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			  </div>
              {% else %}

			<div class="alert alert-{{ message.tags }}  alert-dismissible fade show" role="alert">
				<strong>Voilla </strong> {{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			  </div>
			
			
            {% endif %}
                
			{% endif %}
			{% endfor %}
		
		{% endif %}
        	<form action="/daftar_buku/" method="POST" role="form" class="form-inline">
				{% csrf_token %}
					<div class="form-group">
						<label>Jenis Buku</label>
							<select id="jenis_buku" name="jenis_buku" class="form-control">
								<option value="Novel">Novel</option>
								<option value="Cerpen">Cerpen</option>
								<option value="Majalah">Majalah</option>
								<option value="Komik">Komik</option>
								<option value="Manga">Manga</option>
								<option value="Komputer">Komputer</option>
								<option value="Sekolah">Sekolah</option>
							</select>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-primary" value="submit" />
					</div>
			</form>
				<br />
		<div class="table-responsive">
            <table class="table table-hover">
				<thead>
					<tr>
						<th>#</th>
						<td>Judul Buku</td>
						<td>Jenis Buku</td>
						<td>Penulis</td>
					</tr>
				</thead>
					<tbody>
						{% if daftar_buku %}
							{% for buku in daftar_buku %}
								<tr>
									<td>{{ forloop.counter }}</td>
									<td>{{ buku.judul_buku }}</td>
									<td>{{ buku.jenis_buku }}</td>
									<td>{{ buku.penulis }}</td>
								</tr>
							{% endfor %}
						{% else %}
								<tr>
									<td colspan="3" style="text-align:center;">Tidak ada data buku ..</td>
								</tr>
						{% endif %}
					</tbody>
			</table>
		</div>
			<ul class="pager">
				{% if daftar_buku.has_previous %}
					<li class="previous">
						<a href="?page={{daftar_buku.previous_page_number}}">previous</a>
					</li>
				{% endif %}
					<li class="current">
						Page{{ daftar_buku.number }} of {{ daftar_buku.paginator.num_pages }}.
					</li>
				{% if daftar_buku.has_next %}
					<li class="next">
						<a href="?page={{daftar_buku.page_number}}">next</a>
					</li>
				{% endif %}
			</ul>
	</div>
		</div>
</div>
<center>
	<a class="btn btn-info" href="{% url 'home:down_file' %}">Download file</a>
<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="input-group mb-3">
		<label class="input-group-text" for="inputGroupFile01">Upload</label>
		<input name="fl" type="file" class="form-control" id="inputGroupFile01">
	</div>
	
	<button  class="btn btn-success" type="submit">submit</button>
</form>


</center>
{% endblock %}

home/templates/home/empty.html
{% extends 'base.html' %}


{% block page_title %}
    
{% endblock page_title %}


{% block contents %}
<div style="text-align: center;" class="container-fluid">
    
    <h1>Buku yang anda gagal dipinjam Karena habis dipinjam</h1>
    <a href="{% url 'home:daftar_buku' %}" class="btn btn-info">Cek data buku ?</a>
</div>
    {% endblock contents %}
    
    

home/templates/home/fail.html
{% extends 'base.html' %}


{% block page_title %}
    
{% endblock page_title %}


{% block contents %}
<div style="text-align: center;" class="container-fluid">
    
    <h1>Buku yang anda gagal dipinjam Karena tidak ada dalam Database</h1>
    <a href="{% url 'home:daftar_buku' %}" class="btn btn-info">Cek data buku ?</a>
</div>
    {% endblock contents %}
    
    

home/templates/home/login.html
{% extends "base.html" %}

{%load static%}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}

{% block contents %}
    
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block " style="background:url(https://cdn.trentech.id/static/img/2020/04/kalau-mau-kaya-tanpa-jadi-pengusaha-belajar-coding-bisa-jadi-jawabannya-trentech-seputar-startup_gdghjn_cznmoa-740x394.jpg);background-size:cover;background-position:-180px 0px;"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                	
			{% if messages %}
    
			{% for message in messages %}
			{% if message.tags %} 
            
            {% if message.tags == "warning" %}
                
			<div class="alert alert-danger  alert-dismissible fade show" role="alert">
				<strong>Voilla </strong> {{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			  </div>
              {% else %}

			<div class="alert alert-{{ message.tags }}  alert-dismissible fade show" role="alert">
				<strong>Voilla </strong> {{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			  </div>
			
			
            {% endif %}
                
			{% endif %}
			{% endfor %}
		
		{% endif %}
                                    <form class="user" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                placeholder="Enter Name" name="username" autocomplete="off">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                 placeholder="Password" name="password" autocomplete="off">
                                        </div>
                                        
                                       <button class="btn btn-primary btn-user btn-block" type="submit">LOGIN</button>
                                        
                                     
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'home:register' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock contents %}

home/templates/home/success.html
{% extends 'base.html' %}


{% block page_title %}
    
{% endblock page_title %}


{% block contents %}
<div style="text-align: center;" class="container-fluid">
    <h1>Buku yang anda Pilih berhasil dipinjam ! kembalikan pada waktunya yaa</h1>
    <a href="{% url 'home:databuku' %}" class="btn btn-info">Lihat buku yang dipinjam ?</a>
</div>
    {% endblock contents %}
    
    